"""
Inspect retarget assets to compare project and sample wrapper inputs.
"""

import json
import os

import unreal


ASSETS = [
    "/MutableSample/Character/Animation/RTG_AutoGenerated",
    "/ProjectObject/Human/Hero/RTG_Hero",
    "/MotionMatching/Blueprints/RetargetedCharacters/ABP_GenericRetarget",
    "/ProjectSkeletalCapabilities/MotionMatching/ABP_WorldBodyRetarget",
    "/ProjectObject/Human/Hero/Hero",
]
REPORT_PATH = os.path.join(
    unreal.Paths.project_saved_dir(),
    "Inspection",
    "retarget_asset_report.json",
)
HERO_ASSET_PATH = "/ProjectObject/Human/Hero/Hero"
WORLD_BODY_RETARGET_CLASS = "/ProjectSkeletalCapabilities/MotionMatching/ABP_WorldBodyRetarget.ABP_WorldBodyRetarget_C"


def load_asset(asset_path):
    if hasattr(unreal, "load_asset"):
        asset = unreal.load_asset(asset_path)
        if asset:
            return asset

    asset = unreal.EditorAssetLibrary.load_asset(asset_path)
    if asset:
        return asset

    raise RuntimeError(f"Failed to load asset: {asset_path}")


def dump_asset(asset_path):
    asset = load_asset(asset_path)
    data = {
        "path": asset_path,
        "class": asset.get_class().get_name(),
        "name": asset.get_name(),
        "properties": {},
    }

    interesting = [
        "source_ik_rig_asset",
        "target_ik_rig_asset",
        "ik_retargeter_asset",
        "ik_retargeter_map",
        "ikretargeter_map",
        "retarget_profile",
        "retarget_profiles",
        "chain_settings",
    ]

    for prop_name in interesting:
        try:
            value = asset.get_editor_property(prop_name)
        except Exception:
            continue
        data["properties"][prop_name] = str(value)

    if data["class"] == "IKRetargeter":
        try:
            profile = unreal.RetargetProfileLibrary.copy_retarget_profile_from_retarget_asset(asset)
            data["retarget_profile_copied"] = True
            data["retarget_ik_goals_controller"] = str(
                unreal.RetargetProfileLibrary.get_op_controller_from_retarget_profile(
                    profile, unreal.Name("Retarget IK Goals")
                )
            )
        except Exception as exc:
            data["retarget_profile_copied"] = False
            data["retarget_profile_error"] = str(exc)

    if data["class"] == "AnimBlueprint":
        try:
            cls = unreal.EditorAssetLibrary.load_blueprint_class(asset_path)
            cdo = unreal.get_default_object(cls)
            for prop_name in ["IKRetargeter", "IKRetargeter_Map"]:
                try:
                    value = cdo.get_editor_property(prop_name)
                except Exception:
                    continue
                data["properties"][prop_name] = str(value)
        except Exception as exc:
            data["anim_blueprint_defaults_error"] = str(exc)

    if data["class"] == "ObjectDefinition":
        try:
            meshes = asset.get_editor_property("meshes")
            mesh_rows = []
            for mesh in meshes:
                anim_class = None
                try:
                    anim_class = mesh.anim_class
                except Exception:
                    anim_class = None

                mesh_rows.append({
                    "id": str(mesh.id),
                    "kind": str(mesh.kind),
                    "role": str(mesh.role),
                    "asset": str(mesh.asset),
                    "anim_class": str(anim_class),
                })

            data["mesh_rows"] = mesh_rows
        except Exception as exc:
            data["object_definition_error"] = str(exc)

    return data


def maybe_repair_hero_object_definition():
    if os.environ.get("ALIS_FIX_HERO_OBJECT_DEF") != "1":
        return None

    asset = load_asset(HERO_ASSET_PATH)
    meshes = asset.get_editor_property("meshes")
    target_class = unreal.load_object(None, WORLD_BODY_RETARGET_CLASS)
    if not target_class:
        raise RuntimeError(f"Failed to load target anim class: {WORLD_BODY_RETARGET_CLASS}")

    changed = False
    for index, mesh in enumerate(meshes):
        if str(mesh.id) != "WorldBody":
            continue

        current = None
        try:
            current = mesh.anim_class
        except Exception:
            current = None

        if current != target_class:
            mesh.set_editor_property("anim_class", target_class)
            meshes[index] = mesh
            changed = True

    if changed:
        asset.modify()
        asset.set_editor_property("meshes", meshes)
        saved = unreal.EditorAssetLibrary.save_loaded_asset(asset)
    else:
        saved = True

    return {
        "hero_repair_requested": True,
        "changed": changed,
        "saved": saved,
        "target_anim_class": WORLD_BODY_RETARGET_CLASS,
    }


def main():
    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    report = []
    repair_info = maybe_repair_hero_object_definition()
    if repair_info:
        report.append(repair_info)
    for asset_path in ASSETS:
        try:
            report.append(dump_asset(asset_path))
        except Exception as exc:
            report.append({
                "path": asset_path,
                "error": str(exc),
            })

    with open(REPORT_PATH, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2)

    unreal.log(f"[OK] Wrote retarget inspection report: {REPORT_PATH}")


if __name__ == "__main__":
    main()
