"""
Create or refresh the project-owned WorldBody retarget wrapper.

Why this exists:
- runtime should not depend on vendor sample ABP_GenericRetarget defaults
- ABP_GenericRetarget carries stale sample references we do not own
- we want one project-owned wrapper asset with a narrow retarget map

This helper:
1. duplicates the vendor wrapper into ProjectSkeletalCapabilities content (first run only)
2. rewrites IKRetargeter_Map to the runtime keys we actually use
3. rewires known project Blueprints away from the vendor wrapper
"""

import os

import unreal


SOURCE_BP_PATH = "/MotionMatching/Blueprints/RetargetedCharacters/ABP_GenericRetarget"
TARGET_BP_PATH = "/ProjectSkeletalCapabilities/MotionMatching/ABP_WorldBodyRetarget"
RETARGETER_PATH = "/MutableSample/Character/Animation/RTG_AutoGenerated"
TARGET_KEYS = [
    "DefMeshId=WorldBody",
    "AssemblyRole=WorldBody",
    "RTG_AutoGenerated",
]
BLUEPRINTS_TO_REWIRE = [
    "/ProjectObject/Human/Hero/BP_Hero",
    "/Game/MetaHumans/GrandPa/BP_GrandPa",
]


def resolve_paths(asset_path):
    asset_name = asset_path.rsplit("/", 1)[-1]
    if "." in asset_name:
        package_path = asset_path.rsplit(".", 1)[0]
        object_path = asset_path
    else:
        package_path = asset_path
        object_path = f"{asset_path}.{asset_name}"
    return package_path, object_path


def load_asset(object_path):
    package_path, resolved_object_path = resolve_paths(object_path)
    candidates = [
        package_path,
        resolved_object_path,
    ]

    for candidate in candidates:
        if hasattr(unreal, "load_asset"):
            asset = unreal.load_asset(candidate)
            if asset:
                return asset

        if "." in candidate:
            asset = unreal.load_object(None, candidate)
            if asset:
                return asset

        asset = unreal.EditorAssetLibrary.load_asset(candidate)
        if asset:
            return asset

    raise RuntimeError(f"Failed to load asset: {object_path}")


def load_blueprint_class(asset_path):
    package_path, object_path = resolve_paths(asset_path)
    candidates = [
        package_path,
        object_path,
        f"{package_path}_C",
        f"{object_path}_C",
    ]

    for candidate in candidates:
        loaded_class = unreal.load_object(None, candidate)
        if loaded_class:
            return loaded_class

        loaded_class = unreal.EditorAssetLibrary.load_blueprint_class(candidate)
        if loaded_class:
            return loaded_class

    raise RuntimeError(f"Failed to load Blueprint class: {asset_path}")


def compile_blueprint(blueprint):
    if hasattr(unreal, "KismetEditorUtilities") and hasattr(unreal.KismetEditorUtilities, "compile_blueprint"):
        unreal.KismetEditorUtilities.compile_blueprint(blueprint)
        return

    if hasattr(unreal, "BlueprintEditorLibrary") and hasattr(unreal.BlueprintEditorLibrary, "compile_blueprint"):
        unreal.BlueprintEditorLibrary.compile_blueprint(blueprint)
        return

    raise RuntimeError("No Blueprint compile API was available")


def save_asset(asset_path):
    package_path, _ = resolve_paths(asset_path)
    if not unreal.EditorAssetLibrary.save_asset(package_path, only_if_is_dirty=False):
        raise RuntimeError(f"Failed to save asset: {package_path}")


def ensure_wrapper_blueprint():
    try:
        existing_wrapper = load_asset(TARGET_BP_PATH)
        unreal.log(f"[OK] Wrapper already exists: {TARGET_BP_PATH}")
        return existing_wrapper
    except Exception:
        pass

    source_asset = load_asset(SOURCE_BP_PATH)
    target_name = TARGET_BP_PATH.rsplit("/", 1)[-1]
    target_package = TARGET_BP_PATH.rsplit("/", 1)[0]
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    duplicated = asset_tools.duplicate_asset(target_name, target_package, source_asset)
    if not duplicated:
        raise RuntimeError(f"Failed to duplicate {SOURCE_BP_PATH} -> {TARGET_BP_PATH}")

    unreal.log(f"[OK] Duplicated wrapper: {SOURCE_BP_PATH} -> {TARGET_BP_PATH}")
    return duplicated


def rewrite_wrapper_defaults():
    wrapper_asset = load_asset(TARGET_BP_PATH)
    wrapper_class = load_blueprint_class(TARGET_BP_PATH)
    wrapper_cdo = unreal.get_default_object(wrapper_class)
    retargeter = load_asset(RETARGETER_PATH)

    desired_map = {unreal.Name(key): retargeter for key in TARGET_KEYS}

    wrapper_asset.modify()
    wrapper_cdo.modify()
    wrapper_cdo.set_editor_property("IKRetargeter", retargeter)
    wrapper_cdo.set_editor_property("IKRetargeter_Map", desired_map)
    compile_blueprint(wrapper_asset)
    save_asset(TARGET_BP_PATH)

    unreal.log(
        "[OK] Updated IKRetargeter_Map for "
        f"{TARGET_BP_PATH} with keys: {', '.join(TARGET_KEYS)}"
    )


def find_component_templates(blueprint):
    subsystem = unreal.get_engine_subsystem(unreal.SubobjectDataSubsystem)
    if not subsystem:
        raise RuntimeError("Failed to get SubobjectDataSubsystem")

    handles = subsystem.k2_gather_subobject_data_for_blueprint(blueprint)
    components = []
    for handle in handles:
        data = unreal.SubobjectDataBlueprintFunctionLibrary.get_data(handle)
        component = unreal.SubobjectDataBlueprintFunctionLibrary.get_object_for_blueprint(data, blueprint)
        if component:
            components.append(component)
    return components


def rewire_blueprint_component_anim_classes(asset_path, old_class, new_class):
    package_path, object_path = resolve_paths(asset_path)
    if not unreal.EditorAssetLibrary.does_asset_exist(package_path):
        unreal.log_warning(f"[WARN] Blueprint not found, skipping: {asset_path}")
        return 0

    blueprint = load_asset(object_path)
    changed = 0

    for component in find_component_templates(blueprint):
        if not isinstance(component, unreal.SkeletalMeshComponent):
            continue

        try:
            anim_class = component.get_editor_property("anim_class")
        except Exception:
            continue

        if anim_class != old_class:
            continue

        blueprint.modify()
        component.modify()
        component.set_editor_property("animation_mode", unreal.AnimationMode.ANIMATION_BLUEPRINT)
        component.set_editor_property("anim_class", new_class)
        changed += 1
        unreal.log(
            "[OK] Rewired "
            f"{asset_path}:{component.get_name()} anim_class -> {new_class.get_name()}"
        )

    if changed > 0:
        compile_blueprint(blueprint)
        save_asset(asset_path)

    return changed


def main():
    ensure_wrapper_blueprint()
    rewrite_wrapper_defaults()

    if os.environ.get("ALIS_SKIP_BLUEPRINT_REWIRE", "").strip() == "1":
        unreal.log("[OK] Skipping Blueprint component rewire by request")
        return

    source_class = load_blueprint_class(SOURCE_BP_PATH)
    target_class = load_blueprint_class(TARGET_BP_PATH)

    total_changed = 0
    for blueprint_path in BLUEPRINTS_TO_REWIRE:
        try:
            total_changed += rewire_blueprint_component_anim_classes(
                blueprint_path, source_class, target_class
            )
        except Exception as exc:
            unreal.log_warning(
                f"[WARN] Failed to rewire {blueprint_path}. "
                f"Close the editor and rerun this helper. Details: {exc}"
            )

    unreal.log(
        f"[OK] WorldBody retarget wrapper ready. Rewired component templates: {total_changed}"
    )


if __name__ == "__main__":
    main()
