"""
Create or refresh the project-owned WorldBody retarget wrapper.

Why this exists:
- runtime should not depend on vendor sample ABP_GenericRetarget defaults
- ABP_GenericRetarget carries stale sample references we do not own
- we want one project-owned wrapper asset with a narrow retarget map

This helper:
1. duplicates the vendor wrapper into ProjectSkeletalCapabilities content (first run only)
2. rewrites IKRetargeter_Map to the runtime keys we actually use
"""

import unreal


SOURCE_BP_PATH = "/MotionMatching/Blueprints/RetargetedCharacters/ABP_GenericRetarget"
TARGET_BP_PATH = "/ProjectSkeletalCapabilities/MotionMatching/ABP_WorldBodyRetarget"
RETARGETER_PATH = "/MutableSample/Character/Animation/RTG_AutoGenerated"
TARGET_KEYS = [
    "DefMeshId=WorldBody",
    "AssemblyRole=WorldBody",
    "RTG_AutoGenerated",
]
def resolve_paths(asset_path):
    asset_name = asset_path.rsplit("/", 1)[-1]
    if "." in asset_name:
        package_path = asset_path.rsplit(".", 1)[0]
        object_path = asset_path
    else:
        package_path = asset_path
        object_path = f"{asset_path}.{asset_name}"
    return package_path, object_path


def load_asset(object_path):
    package_path, resolved_object_path = resolve_paths(object_path)
    candidates = [
        package_path,
        resolved_object_path,
    ]

    for candidate in candidates:
        if hasattr(unreal, "load_asset"):
            asset = unreal.load_asset(candidate)
            if asset:
                return asset

        if "." in candidate:
            asset = unreal.load_object(None, candidate)
            if asset:
                return asset

        asset = unreal.EditorAssetLibrary.load_asset(candidate)
        if asset:
            return asset

    raise RuntimeError(f"Failed to load asset: {object_path}")


def load_blueprint_class(asset_path):
    package_path, object_path = resolve_paths(asset_path)
    candidates = [
        package_path,
        object_path,
        f"{package_path}_C",
        f"{object_path}_C",
    ]

    for candidate in candidates:
        loaded_class = unreal.load_object(None, candidate)
        if loaded_class:
            return loaded_class

        loaded_class = unreal.EditorAssetLibrary.load_blueprint_class(candidate)
        if loaded_class:
            return loaded_class

    raise RuntimeError(f"Failed to load Blueprint class: {asset_path}")


def compile_blueprint(blueprint):
    if hasattr(unreal, "KismetEditorUtilities") and hasattr(unreal.KismetEditorUtilities, "compile_blueprint"):
        unreal.KismetEditorUtilities.compile_blueprint(blueprint)
        return

    if hasattr(unreal, "BlueprintEditorLibrary") and hasattr(unreal.BlueprintEditorLibrary, "compile_blueprint"):
        unreal.BlueprintEditorLibrary.compile_blueprint(blueprint)
        return

    raise RuntimeError("No Blueprint compile API was available")


def save_asset(asset_path):
    package_path, _ = resolve_paths(asset_path)
    if not unreal.EditorAssetLibrary.save_asset(package_path, only_if_is_dirty=False):
        raise RuntimeError(f"Failed to save asset: {package_path}")


def ensure_wrapper_blueprint():
    try:
        existing_wrapper = load_asset(TARGET_BP_PATH)
        unreal.log(f"[OK] Wrapper already exists: {TARGET_BP_PATH}")
        return existing_wrapper
    except Exception:
        pass

    source_asset = load_asset(SOURCE_BP_PATH)
    target_name = TARGET_BP_PATH.rsplit("/", 1)[-1]
    target_package = TARGET_BP_PATH.rsplit("/", 1)[0]
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    duplicated = asset_tools.duplicate_asset(target_name, target_package, source_asset)
    if not duplicated:
        raise RuntimeError(f"Failed to duplicate {SOURCE_BP_PATH} -> {TARGET_BP_PATH}")

    unreal.log(f"[OK] Duplicated wrapper: {SOURCE_BP_PATH} -> {TARGET_BP_PATH}")
    return duplicated


def rewrite_wrapper_defaults():
    wrapper_asset = load_asset(TARGET_BP_PATH)
    wrapper_class = load_blueprint_class(TARGET_BP_PATH)
    wrapper_cdo = unreal.get_default_object(wrapper_class)
    retargeter = load_asset(RETARGETER_PATH)

    desired_map = {unreal.Name(key): retargeter for key in TARGET_KEYS}

    wrapper_asset.modify()
    wrapper_cdo.modify()
    wrapper_cdo.set_editor_property("IKRetargeter", retargeter)
    wrapper_cdo.set_editor_property("IKRetargeter_Map", desired_map)
    compile_blueprint(wrapper_asset)
    save_asset(TARGET_BP_PATH)

    unreal.log(
        "[OK] Updated IKRetargeter_Map for "
        f"{TARGET_BP_PATH} with keys: {', '.join(TARGET_KEYS)}"
    )


def main():
    ensure_wrapper_blueprint()
    rewrite_wrapper_defaults()
    unreal.log("[OK] WorldBody retarget wrapper ready")


if __name__ == "__main__":
    main()
