// Copyright ALIS. All Rights Reserved.
// License terms: see repository root LICENSE.

#pragma once

#include "CoreMinimal.h"
#include "Audio/AudioTypes.h"
#include "AudioPresetDefinition.generated.h"

/**
 * Attenuation settings block for audio presets.
 * All fields optional -- presence of the block means override sound asset defaults.
 */
USTRUCT(BlueprintType)
struct PROJECTOBJECTCAPABILITIES_API FAudioAttenuationConfig
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attenuation")
	FString Shape;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attenuation")
	float InnerRadius = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attenuation")
	float FalloffDistance = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attenuation")
	float ConeAngle = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attenuation")
	float ConeFalloffAngle = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attenuation")
	FString Spatialization;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attenuation")
	float BinauralRadius = 0.0f;

	// True if attenuation block was present in JSON. Set by parser.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attenuation")
	bool bIsSet = false;

	bool IsValid() const { return bIsSet; }
};

/**
 * Generated asset from AUDIO_*.json files.
 * Single source of truth for all audio playback settings.
 *
 * Auto-generated by x-alis-generator from audio.schema.json.
 * Do not edit generated assets directly - modify the source JSON.
 */
UCLASS(BlueprintType)
class PROJECTOBJECTCAPABILITIES_API UAudioPresetDefinition : public UObject
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	FName AudioId;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	TArray<FAudioTrack> Tracks;

	// -------------------------------------------------------------------------
	// Sound Source Transform (relative to owning actor)
	// -------------------------------------------------------------------------

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio|Spatial")
	FVector SourceOffset = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio|Spatial")
	FRotator SourceRotation = FRotator::ZeroRotator;

	// Attenuation (nested object -- omit block to use sound asset defaults)
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	FAudioAttenuationConfig Attenuation;

	// -------------------------------------------------------------------------
	// Helpers
	// -------------------------------------------------------------------------

	bool HasSourceTransform() const
	{
		return !SourceOffset.IsZero() || !SourceRotation.IsZero();
	}

	/** Find track by ID. Returns nullptr if not found. */
	const FAudioTrack* FindTrack(const FString& TrackId) const;

	// --- Generator metadata ---
	UPROPERTY(VisibleAnywhere, Category = "Generation", AssetRegistrySearchable)
	bool bGenerated = false;

	UPROPERTY(VisibleAnywhere, Category = "Generation", AssetRegistrySearchable)
	int32 GeneratorVersion = 0;

	UPROPERTY(VisibleAnywhere, Category = "Generation", AssetRegistrySearchable)
	FString SourceJsonPath;

	UPROPERTY(VisibleAnywhere, Category = "Generation", AssetRegistrySearchable)
	FString SourceJsonHash;
};
