// Copyright ALIS. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Audio/AudioTypes.h"
#include "AudioPresetDefinition.generated.h"

/**
 * Generated asset from AUDIO_*.json files.
 * Contains track list for an audio-capable object (gramophone, radio, etc.).
 *
 * Auto-generated by x-alis-generator from audio.schema.json.
 * Do not edit generated assets directly - modify the source JSON.
 */
UCLASS(BlueprintType)
class PROJECTOBJECTCAPABILITIES_API UAudioPresetDefinition : public UObject
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	FName AudioId;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	TArray<FAudioTrack> Tracks;

	// Spatial attenuation: full volume within InnerRadius (cm)
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	float InnerRadius = 200.f;

	// Distance beyond InnerRadius where sound fades to silence (cm)
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	float FalloffDistance = 1500.f;

	// --- Generator metadata ---
	UPROPERTY(VisibleAnywhere, Category = "Generation", AssetRegistrySearchable)
	bool bGenerated = false;

	UPROPERTY(VisibleAnywhere, Category = "Generation", AssetRegistrySearchable)
	int32 GeneratorVersion = 0;

	UPROPERTY(VisibleAnywhere, Category = "Generation", AssetRegistrySearchable)
	FString SourceJsonPath;

	UPROPERTY(VisibleAnywhere, Category = "Generation", AssetRegistrySearchable)
	FString SourceJsonHash;

	/** Find track by ID. Returns nullptr if not found. */
	const FAudioTrack* FindTrack(const FString& TrackId) const;
};
